### ISSUE TITLE
Discarding unimportant parameters

### ISSUE THREAD

**Issue by RoryBarnes** [dflemin3/approxposterior#25]
After each iteration, the code could run a check for which parameters have no impact on the likelihood, and they could be removed to speed up the next iteration. A user-defined parameter (or two) would need to be defined to set tolerances for such pruning. For cases with dozens or hundreds of independent variables, the removal of unimportant parameters could save significant computational time.

**Comment by dflemin3** [comment]
We've discussed this offline previously and I've thought about this over the past few days. I think I am going to leave it up to the user to decide what parameters are unimportant because I don't want approxposterior to modify someone's model automatically after the fact. george has nice capability to freeze and thaw parameters that could accomplish what you intended, but I think the user can take care of that. Let me know if you have any ideas to accomplish this!
